import type { JournalMatch } from "@/lib/journals/types";

/*
 * INTERIM — used only by the mock workspace (lib/workspace/journals.ts) until Phase 4
 * replaces it with real backend data. The journals screen no longer uses this file after Step 3.2b.
 * Fictional demo journals — every value here is prototype data.
 * similarityScore / matchedTopics are deliberately 0 / empty: they are not invented.
 */
export const MOCK_JOURNAL_MATCHES: JournalMatch[] = [
  {
    journalId: "jaas",
    name: "Journal of Applied Agricultural Systems",
    shortName: "JAAS",
    publisher: "Demo Academic Press",
    rank: 1,
    scopeFit: "strong",
    similarityScore: 0,
    matchedTopics: [],
    apcUsd: 3200,
    openAccess: "hybrid",
    reviewDaysAvg: 120,
    indexes: ["scopus", "wos"],
    requirementsSummary: ["العنوان ≤ 15 كلمة", "الملخص ≤ 250 كلمة", "30–60 مرجعًا", "Highlights مطلوبة"],
    sourceUrl: "https://example.com/demo-journal-guidelines/jaas",
    sourceIsDemo: true,
    extractionConfidence: "high",
    needsHumanReview: true,
    lastCheckedAt: "2026-09-12",
  },
  {
    journalId: "sfvr",
    name: "Smart Farming & Vision Research",
    shortName: "SFVR",
    publisher: "Demo Research Publishing",
    rank: 2,
    scopeFit: "strong",
    similarityScore: 0,
    matchedTopics: [],
    apcUsd: 1450,
    openAccess: "full",
    reviewDaysAvg: 38,
    indexes: ["scopus", "wos"],
    requirementsSummary: ["العنوان ≤ 20 كلمة", "الملخص ≤ 300 كلمة", "≤ 50 مرجعًا", "بيان إتاحة البيانات مطلوب"],
    sourceUrl: "https://example.com/demo-journal-guidelines/sfvr",
    sourceIsDemo: true,
    extractionConfidence: "high",
    needsHumanReview: true,
    lastCheckedAt: "2026-09-18",
  },
  {
    journalId: "car",
    name: "Computational Agriculture Review",
    shortName: "CAR",
    publisher: "Demo Science Group",
    rank: 3,
    scopeFit: "good",
    similarityScore: 0,
    matchedTopics: [],
    apcUsd: 900,
    openAccess: "full",
    reviewDaysAvg: 55,
    indexes: ["scopus"],
    requirementsSummary: ["العنوان ≤ 18 كلمة", "الملخص ≤ 250 كلمة", "35–60 مرجعًا", "قالب LaTeX مطلوب"],
    sourceUrl: "https://example.com/demo-journal-guidelines/car",
    sourceIsDemo: true,
    extractionConfidence: "medium",
    needsHumanReview: false,
    lastCheckedAt: "2026-09-15",
  },
  {
    journalId: "dam",
    name: "Digital Agriculture Methods",
    shortName: "DAM",
    publisher: "Demo Scholarly Press",
    rank: 4,
    scopeFit: "possible",
    similarityScore: 0,
    matchedTopics: [],
    apcUsd: 0,
    openAccess: "subscription",
    reviewDaysAvg: 75,
    indexes: ["wos"],
    requirementsSummary: ["≤ 5,000 كلمة", "الملخص ≤ 200 كلمة", "≤ 40 مرجعًا"],
    sourceUrl: "https://example.com/demo-journal-guidelines/dam",
    sourceIsDemo: true,
    extractionConfidence: "low",
    needsHumanReview: true,
    lastCheckedAt: "2026-09-10",
  },
];