import type { JournalMatch } from "@/lib/journals/types";

/* Fictional demo journals — every value here is prototype data. */
export const MOCK_JOURNAL_MATCHES: JournalMatch[] = [
  {
    journalId: "jaas",
    name: "Journal of Applied Agricultural Systems",
    shortName: "JAAS",
    publisher: "Demo Academic Press",
    scopeFit: "strong",
    scopeReason:
      "نطاقها يغطي تطبيقات الرؤية الحاسوبية في الأنظمة الزراعية الميدانية، وتنشر أبحاثًا عن تشخيص أمراض النباتات من الصور، وهو محور بحثك.",
    apcUsd: 3200,
    openAccess: "hybrid",
    reviewDaysAvg: 120,
    indexes: ["scopus", "wos"],
    requirementsSummary: ["العنوان ≤ 15 كلمة", "الملخص ≤ 250 كلمة", "30–60 مرجعًا", "Highlights مطلوبة"],
    sourceUrl: "https://example.com/demo-journal-guidelines/jaas",
    sourceIsDemo: true,
    extractionConfidence: "high",
    needsHumanReview: true,
    lastCheckedAt: "2026-09-12",
  },
  {
    journalId: "sfvr",
    name: "Smart Farming & Vision Research",
    shortName: "SFVR",
    publisher: "Demo Research Publishing",
    scopeFit: "strong",
    scopeReason:
      "تركّز على نماذج الرؤية الخفيفة وتشغيلها في الحقل، وهو جوهر مساهمة بحثك في النموذج خفيف الوزن.",
    apcUsd: 1450,
    openAccess: "full",
    reviewDaysAvg: 38,
    indexes: ["scopus", "wos"],
    requirementsSummary: ["العنوان ≤ 20 كلمة", "الملخص ≤ 300 كلمة", "≤ 50 مرجعًا", "بيان إتاحة البيانات مطلوب"],
    sourceUrl: "https://example.com/demo-journal-guidelines/sfvr",
    sourceIsDemo: true,
    extractionConfidence: "high",
    needsHumanReview: true,
    lastCheckedAt: "2026-09-18",
  },
  {
    journalId: "car",
    name: "Computational Agriculture Review",
    shortName: "CAR",
    publisher: "Demo Science Group",
    scopeFit: "good",
    scopeReason:
      "تغطي النماذج الحاسوبية في الزراعة عمومًا؛ بحثك ضمن نطاقها، لكن تركيزها على النمذجة والمحاكاة أكثر من الرؤية الحاسوبية.",
    apcUsd: 900,
    openAccess: "full",
    reviewDaysAvg: 55,
    indexes: ["scopus"],
    requirementsSummary: ["العنوان ≤ 18 كلمة", "الملخص ≤ 250 كلمة", "35–60 مرجعًا", "قالب LaTeX مطلوب"],
    sourceUrl: "https://example.com/demo-journal-guidelines/car",
    sourceIsDemo: true,
    extractionConfidence: "medium",
    needsHumanReview: false,
    lastCheckedAt: "2026-09-15",
  },
  {
    journalId: "dam",
    name: "Digital Agriculture Methods",
    shortName: "DAM",
    publisher: "Demo Scholarly Press",
    scopeFit: "possible",
    scopeReason:
      "تنشر أوراقًا منهجية قصيرة في الزراعة الرقمية؛ الموضوع قريب، لكن طول بحثك (7,850 كلمة) يتجاوز الحد المعتاد لديها.",
    apcUsd: 0,
    openAccess: "subscription",
    reviewDaysAvg: 75,
    indexes: ["wos"],
    requirementsSummary: ["≤ 5,000 كلمة", "الملخص ≤ 200 كلمة", "≤ 40 مرجعًا"],
    sourceUrl: "https://example.com/demo-journal-guidelines/dam",
    sourceIsDemo: true,
    extractionConfidence: "low",
    needsHumanReview: true,
    lastCheckedAt: "2026-09-10",
  },
];