/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/manuscripts/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Manuscript
         * @description Upload and parse a DOCX manuscript.
         *
         *     The parsed result is saved and gets a manuscript_id. Uploading the
         *     exact same file again returns the saved parse without re-parsing.
         */
        post: operations["upload_manuscript_manuscripts_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manuscripts/{manuscript_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Manuscript */
        get: operations["get_manuscript_manuscripts__manuscript_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Match Manuscript
         * @description Rank stored journals for a stored manuscript. The paper is never re-parsed.
         */
        post: operations["match_manuscript_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Journals
         * @description All journals, as cards for the browse/compare screens.
         */
        get: operations["list_journals_journals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journals/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Queue
         * @description Journals the agent was unsure about, waiting for a human to check.
         */
        get: operations["review_queue_journals_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journals/review-queue/{journal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review Item
         * @description One queued draft, including extracted fields, confidence, and source excerpts.
         */
        get: operations["get_review_item_journals_review_queue__journal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit Review Item
         * @description Replace the draft spec after reviewer correction. Does not approve it.
         */
        patch: operations["edit_review_item_journals_review_queue__journal_id__patch"];
        trace?: never;
    };
    "/journals/review-queue/{journal_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Review Item
         * @description Approve a reviewed draft and promote it to the journal catalog.
         *
         *     Intended for authorized reviewers; protect before public deployment.
         */
        post: operations["approve_review_item_journals_review_queue__journal_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journals/review-queue/{journal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Review Item
         * @description Reject a queued draft without adding it to the journal catalog.
         */
        post: operations["reject_review_item_journals_review_queue__journal_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journals/{journal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Journal
         * @description Full requirements of one journal, including per-field sources.
         */
        get: operations["get_journal_journals__journal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate
         * @description Submission checklist for one manuscript against one journal.
         *
         *     Switch Journal = call this again with another journal_id. The manuscript
         *     is never re-parsed, so switching is instant.
         */
        post: operations["validate_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validate/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare
         * @description Readiness summary against several journals at once, for the compare/switch screens.
         */
        post: operations["compare_validate_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggestions
         * @description AI suggestions for one manuscript + journal: scope fit, plus drafts that
         *     help fix failed checklist rules. Kept separate from /validate so the
         *     checklist stays instant and deterministic. Nothing is applied automatically.
         */
        post: operations["suggestions_suggestions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions/{suggestion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Decide
         * @description The researcher accepts or rejects a suggestion. The backend only records the choice.
         */
        patch: operations["decide_suggestions__suggestion_id__patch"];
        trace?: never;
    };
    "/llm/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Llm Usage
         * @description LLMOps dashboard data: calls, cache hits, failures, tokens and estimated cost per task and model.
         */
        get: operations["llm_usage_llm_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/citations/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Convert
         * @description Propose the manuscript's references in another citation style
         *     (the "Convert references" fix in the checklist). Nothing is applied:
         *     the researcher reviews the converted list and accepts it in the workspace.
         */
        post: operations["convert_citations_convert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check for deployment, plus whether LLM features can run.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Block */
        Block: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Text */
            text: string;
            /** Section */
            section?: string | null;
            /** Word Count */
            word_count: number;
            /** Paragraph Index */
            paragraph_index?: number | null;
        };
        /** Body_upload_manuscript_manuscripts_upload_post */
        Body_upload_manuscript_manuscripts_upload_post: {
            /** File */
            file: string;
        };
        /** CitationConversion */
        CitationConversion: {
            /** Status */
            status: string;
            /** Message */
            message?: string | null;
            from_style: components["schemas"]["CitationStyle"];
            to_style: components["schemas"]["CitationStyle"];
            /** References */
            references?: components["schemas"]["ConvertedReference"][];
            /** Verified */
            verified?: boolean | null;
            /** Failed Indexes */
            failed_indexes?: number[];
            /** Model */
            model?: string | null;
        };
        /**
         * CitationStyle
         * @enum {string}
         */
        CitationStyle: "apa" | "ieee" | "mla" | "chicago" | "unknown";
        /** CompareRequest */
        CompareRequest: {
            /** Manuscript Id */
            manuscript_id: string;
            /** Journal Ids */
            journal_ids: string[];
        };
        /** ConvertRequest */
        ConvertRequest: {
            /** Manuscript Id */
            manuscript_id: string;
            to_style?: components["schemas"]["CitationStyle"] | null;
            /** Journal Id */
            journal_id?: string | null;
        };
        /** ConvertedReference */
        ConvertedReference: {
            /** Original Index */
            original_index: number;
            /** Original */
            original: string;
            /** Converted */
            converted: string;
            /** In Text */
            in_text?: string | null;
            /** Missing Fields */
            missing_fields?: string[];
            /** Block Id */
            block_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HardConstraint
         * @description Measurable, explicitly-stated rules. No judgment calls here.
         */
        HardConstraint: {
            /** Max Page Count */
            max_page_count?: number | null;
            /** Max Word Count */
            max_word_count?: number | null;
            /** Max Title Words */
            max_title_words?: number | null;
            /** Reference Range */
            reference_range?: [
                number,
                number
            ] | null;
            required_citation_style?: components["schemas"]["CitationStyle"] | null;
            /** Required Template */
            required_template?: string | null;
            /** Max Abstract Words */
            max_abstract_words?: number | null;
            /** Keyword Range */
            keyword_range?: [
                number,
                number
            ] | null;
            /** Max Tables */
            max_tables?: number | null;
            /** Max Figures */
            max_figures?: number | null;
            /** Highlights Range */
            highlights_range?: [
                number,
                number
            ] | null;
            /** Required Statements */
            required_statements?: string[];
            /** Required Sections */
            required_sections?: string[];
        };
        /**
         * JournalMatchView
         * @description One ranked recommendation (POST /match).
         */
        JournalMatchView: {
            /** Journal Id */
            journal_id: string;
            /** Name */
            name: string;
            /** Short Name */
            short_name?: string | null;
            /** Publisher */
            publisher: string;
            /**
             * Access Model
             * @default unknown
             * @enum {string}
             */
            access_model: "open_access" | "hybrid" | "subscription" | "unknown";
            /** Apc Usd */
            apc_usd?: number | null;
            /** Review Days Avg */
            review_days_avg?: number | null;
            /** Indexes */
            indexes?: string[];
            /** Requirements Summary */
            requirements_summary?: string[];
            /** Source Url */
            source_url: string;
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
            /** Extraction Confidence */
            extraction_confidence: number;
            /**
             * Extraction Confidence Level
             * @enum {string}
             */
            extraction_confidence_level: "high" | "medium" | "low";
            /** Needs Human Review */
            needs_human_review: boolean;
            /**
             * Last Checked At
             * Format: date-time
             */
            last_checked_at: string;
            /** Rank */
            rank: number;
            /** Match Score */
            match_score: number;
            /** Similarity Score */
            similarity_score: number;
            /**
             * Scope Fit
             * @enum {string}
             */
            scope_fit: "strong" | "good" | "possible";
            /** Reasons */
            reasons?: string[];
            /** Matched Topics */
            matched_topics?: string[];
        };
        /** JournalReadiness */
        JournalReadiness: {
            /** Journal Id */
            journal_id: string;
            /** Journal Name */
            journal_name: string;
            summary: components["schemas"]["ReadinessSummary"];
        };
        /**
         * JournalRequirementSpec
         * @description The single artifact this module exists to produce.
         *     One instance per journal, written to Postgres (+ pgvector for
         *     scope_embedding) after every successful scrape.
         */
        JournalRequirementSpec: {
            /** Journal Id */
            journal_id: string;
            /** Name */
            name: string;
            /** Publisher */
            publisher: string;
            /** Source Url */
            source_url: string;
            hard_constraints: components["schemas"]["HardConstraint"];
            /** Scope Embedding */
            scope_embedding?: number[];
            /** Apc Usd */
            apc_usd?: number | null;
            /** Review Speed Days Avg */
            review_speed_days_avg?: number | null;
            /** Scope Description */
            scope_description: string;
            /** Extraction Confidence */
            extraction_confidence: number;
            /**
             * Needs Human Review
             * @default false
             */
            needs_human_review: boolean;
            /** Topics */
            topics?: string[];
            /** Accepted Article Types */
            accepted_article_types?: string[];
            /** Languages */
            languages?: string[];
            /** Access Model */
            access_model: string;
            /**
             * Last Scraped At
             * Format: date-time
             */
            last_scraped_at?: string;
            /** Short Name */
            short_name?: string | null;
            /**
             * Aims
             * @default
             */
            aims: string;
            /** Indexes */
            indexes?: string[];
            /** Field Confidences */
            field_confidences?: {
                [key: string]: number;
            };
            /** Field Excerpts */
            field_excerpts?: {
                [key: string]: string;
            };
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
        };
        /**
         * JournalSummary
         * @description One journal as shown in lists (GET /journals).
         */
        JournalSummary: {
            /** Journal Id */
            journal_id: string;
            /** Name */
            name: string;
            /** Short Name */
            short_name?: string | null;
            /** Publisher */
            publisher: string;
            /**
             * Access Model
             * @default unknown
             * @enum {string}
             */
            access_model: "open_access" | "hybrid" | "subscription" | "unknown";
            /** Apc Usd */
            apc_usd?: number | null;
            /** Review Days Avg */
            review_days_avg?: number | null;
            /** Indexes */
            indexes?: string[];
            /** Requirements Summary */
            requirements_summary?: string[];
            /** Source Url */
            source_url: string;
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
            /** Extraction Confidence */
            extraction_confidence: number;
            /**
             * Extraction Confidence Level
             * @enum {string}
             */
            extraction_confidence_level: "high" | "medium" | "low";
            /** Needs Human Review */
            needs_human_review: boolean;
            /**
             * Last Checked At
             * Format: date-time
             */
            last_checked_at: string;
        };
        /** ManuscriptParsedData */
        ManuscriptParsedData: {
            /** Title */
            title: string;
            /** Title Word Count */
            title_word_count: number;
            /** Abstract */
            abstract: string;
            /** Abstract Word Count */
            abstract_word_count: number;
            /** Keywords */
            keywords: string[];
            /** Full Document Word Count */
            full_document_word_count: number;
            /** Main Text Word Count */
            main_text_word_count: number;
            /** Reference Count */
            reference_count: number;
            /** References */
            references: string[];
            /** Table Count */
            table_count: number;
            /** Figure Count */
            figure_count: number;
            /** Sections */
            sections: components["schemas"]["SectionInfo"][];
            /** Blocks */
            blocks?: components["schemas"]["Block"][];
            /** Full Text */
            full_text: string;
        };
        /**
         * ManuscriptRecord
         * @description What the backend stores for every uploaded manuscript.
         */
        ManuscriptRecord: {
            /** Manuscript Id */
            manuscript_id: string;
            /** Filename */
            filename: string;
            /**
             * File Format
             * @default docx
             * @enum {string}
             */
            file_format: "docx" | "pdf" | "latex";
            /** Content Hash */
            content_hash: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at?: string;
            parsed: components["schemas"]["ManuscriptParsedData"];
        };
        /**
         * ManuscriptUploadResponse
         * @description Response of POST /manuscripts/upload.
         */
        ManuscriptUploadResponse: {
            /** Manuscript Id */
            manuscript_id: string;
            /** Filename */
            filename: string;
            parsed: components["schemas"]["ManuscriptParsedData"];
            /**
             * From Cache
             * @default false
             */
            from_cache: boolean;
        };
        /** MatchPreferences */
        MatchPreferences: {
            /** Article Type */
            article_type?: string | null;
            /** Language */
            language?: string | null;
            /**
             * Open Access Only
             * @default false
             */
            open_access_only: boolean;
            /** Max Apc */
            max_apc?: number | null;
            /** Apc Currency */
            apc_currency?: string | null;
            /** Preferred Publishers */
            preferred_publishers?: string[];
            /** Preferred Journals */
            preferred_journals?: string[];
            /**
             * Top K
             * @default 5
             */
            top_k: number;
            /**
             * Prefer Open Access
             * @default false
             */
            prefer_open_access: boolean;
            /** Max Review Days */
            max_review_days?: number | null;
            /** Required Indexes */
            required_indexes?: string[];
        };
        /** MatchRequest */
        MatchRequest: {
            /** Manuscript Id */
            manuscript_id: string;
            preferences?: components["schemas"]["MatchPreferences"];
        };
        /** ReadinessSummary */
        ReadinessSummary: {
            /** Failed Count */
            failed_count: number;
            /** Review Count */
            review_count: number;
            /** Passed Count */
            passed_count: number;
            /** Total */
            total: number;
            /** Meets Hard Requirements */
            meets_hard_requirements: boolean;
            /** Is Fully Ready */
            is_fully_ready: boolean;
        };
        /** RequirementResult */
        RequirementResult: {
            /** Rule Id */
            rule_id: string;
            /** Field */
            field: string;
            /** Label */
            label: string;
            /** Requirement */
            requirement: string;
            /** Measured */
            measured?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "failed" | "review";
            /**
             * Severity
             * @default hard
             * @enum {string}
             */
            severity: "hard" | "soft";
            /** Message */
            message: string;
            /** Block Ids */
            block_ids?: string[];
            suggested_fix?: components["schemas"]["SuggestedFix"] | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Source Excerpt */
            source_excerpt?: string | null;
            /** Source Url */
            source_url?: string | null;
            /**
             * Confidence Level
             * @enum {string}
             */
            readonly confidence_level: "high" | "medium" | "low";
        };
        /** ReviewApproveRequest */
        ReviewApproveRequest: {
            draft_spec?: components["schemas"]["JournalRequirementSpec"] | null;
            /** Review Notes */
            review_notes?: string | null;
        };
        /** ReviewEditRequest */
        ReviewEditRequest: {
            draft_spec: components["schemas"]["JournalRequirementSpec"];
            /** Review Notes */
            review_notes?: string | null;
        };
        /**
         * ReviewQueueItem
         * @description What gets shown to a human when extraction_confidence is below
         *     threshold. Kept separate from JournalRequirementSpec so the API
         *     can return "here's what we think, here's why we're unsure."
         */
        ReviewQueueItem: {
            /** Journal Id */
            journal_id: string;
            /** Name */
            name: string;
            /** Source Url */
            source_url: string;
            draft_spec?: components["schemas"]["JournalRequirementSpec"] | null;
            /** Low Confidence Fields */
            low_confidence_fields: string[];
            /** Raw Extract Notes */
            raw_extract_notes?: string | null;
            /** Review Notes */
            review_notes?: string | null;
            /**
             * Status
             * @default pending
             */
            status: string;
        };
        /** ReviewRejectRequest */
        ReviewRejectRequest: {
            /** Reason */
            reason?: string | null;
        };
        /** SectionInfo */
        SectionInfo: {
            /** Name */
            name: string;
            /** Text */
            text: string;
            /** Word Count */
            word_count: number;
            /** Block Ids */
            block_ids?: string[];
        };
        /**
         * SuggestedFix
         * @description An action the UI can offer. Never applied without the researcher's approval.
         */
        SuggestedFix: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Params */
            params?: {
                [key: string]: string;
            };
        };
        /**
         * Suggestion
         * @description AI recommendation (~ frontend WarraqSuggestion). Always optional for the researcher.
         */
        Suggestion: {
            /** Suggestion Id */
            suggestion_id: string;
            /** Kind */
            kind?: string | null;
            /** Rule Id */
            rule_id?: string | null;
            /** Field */
            field: string;
            /** Label */
            label: string;
            /** Title */
            title: string;
            /** Rationale */
            rationale: string;
            /** Block Id */
            block_id?: string | null;
            /** Before */
            before?: string | null;
            /** After */
            after?: string | null;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "accepted" | "rejected";
            /** Model */
            model?: string | null;
        };
        /** SuggestionDecision */
        SuggestionDecision: {
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "rejected" | "pending";
        };
        /** SuggestionsRequest */
        SuggestionsRequest: {
            /** Manuscript Id */
            manuscript_id: string;
            /** Journal Id */
            journal_id: string;
            /**
             * Refresh
             * @default false
             */
            refresh: boolean;
        };
        /** SuggestionsResponse */
        SuggestionsResponse: {
            /** Manuscript Id */
            manuscript_id: string;
            /** Journal Id */
            journal_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "stored" | "unavailable" | "error";
            /** Message */
            message?: string | null;
            /** Suggestions */
            suggestions: components["schemas"]["Suggestion"][];
        };
        /** ValidateRequest */
        ValidateRequest: {
            /** Manuscript Id */
            manuscript_id: string;
            /** Journal Id */
            journal_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValidationReport
         * @description Response of POST /validate. Switch Journal = same call with another journal_id.
         */
        ValidationReport: {
            /** Manuscript Id */
            manuscript_id: string;
            /** Journal Id */
            journal_id: string;
            /** Results */
            results: components["schemas"]["RequirementResult"][];
            /** Suggestions */
            suggestions?: components["schemas"]["Suggestion"][];
            summary: components["schemas"]["ReadinessSummary"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_manuscript_manuscripts_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_manuscript_manuscripts_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManuscriptUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manuscript_manuscripts__manuscript_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manuscript_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManuscriptRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_manuscript_match_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalMatchView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_journals_journals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalSummary"][];
                };
            };
        };
    };
    review_queue_journals_review_queue_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_item_journals_review_queue__journal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_review_item_journals_review_queue__journal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_review_item_journals_review_queue__journal_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journal_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReviewApproveRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_review_item_journals_review_queue__journal_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journal_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReviewRejectRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_journal_journals__journal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalRequirementSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_validate_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalReadiness"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggestions_suggestions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_suggestions__suggestion_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suggestion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_usage_llm_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    convert_citations_convert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConvertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CitationConversion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
